<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('trainings', function (Blueprint $table) {
            $table->id();
            $table->text('type_of_training')->nullable();
            $table->text('venue')->nullable();
            $table->text('name_of_range')->nullable();
            $table->text('training_no')->nullable();
            $table->date('training_s_date')->nullable();
            $table->date('training_e_date')->nullable();
            $table->time('training_s_time')->nullable();
            $table->time('training_e_time')->nullable();
            $table->text('office_no')->nullable();
            $table->text('building')->nullable();
            $table->text('block')->nullable();
            $table->text('area')->nullable();
            $table->text('city')->nullable();
            $table->text('photo')->nullable();
            $table->text('email')->nullable();
            $table->text('website')->nullable();
            $table->text('pin')->nullable();
            $table->text('gps')->nullable();
            //Details Of CRO
            $table->text('cro_name')->nullable();
            $table->text('cro_cell')->nullable();
            $table->text('email_cro')->nullable();
            $table->text('organized_by')->nullable();
            $table->text('branch')->nullable();
            $table->text('demo')->nullable();
            $table->text('duration')->nullable();
            $table->text('booking_attach')->nullable();
            $table->text('all_types_covered')->nullable();
            $table->text('reports_submitted')->nullable();
            //Correspondence
            $table->text('booking_request')->nullable();
            $table->text('range_allocation_attach')->nullable();
            $table->date('booking_request_date')->nullable();
            $table->text('copy_booking_attach')->nullable();
            $table->boolean('email_active_check')->default(false);
            $table->text('send_email_active')->nullable();
            $table->boolean('email_inactive_check')->default(false);
            $table->text('send_email_inactive')->nullable();
            $table->boolean('email_all_check')->default(false);
            $table->text('send_email_all')->nullable();
            $table->text('guards_respective')->nullable();
            $table->date('date_allocation_letter')->nullable();
            $table->text('poc_name')->nullable();
            $table->text('poc_desig')->nullable();
            $table->text('poc_fax')->nullable();
            $table->text('poc_phone')->nullable();
            $table->text('poc_mobile')->nullable();
            $table->text('poc_web')->nullable();
            $table->text('poc_email')->nullable();
            $table->text('poc_loc')->nullable();
            $table->text('poc_document')->nullable();
            $table->text('system_id')->nullable();
            $table->text('other_info')->nullable();
            //General Security Duties
            $table->boolean('general_check')->default(false);
            $table->text('general_video')->nullable();
            $table->text('general_literature')->nullable();
            $table->text('general_trainer_name')->nullable();
            $table->text('general_trainer_desig')->nullable();
            $table->text('general_trainer_email')->nullable();
            $table->text('general_trainer_cell')->nullable();
            $table->text('general_trainer_office')->nullable();
            $table->text('general_trainer_rhq')->nullable();
            $table->text('general_trainer_region')->nullable();
            $table->text('general_trainer_cards')->nullable();
            $table->text('general_guards_cards')->nullable();
            //Weapon Handling Techniques
            $table->boolean('weapon_check')->default(false);
            $table->text('weapon_video')->nullable();
            $table->text('weapon_literature')->nullable();
            $table->text('weapon_trainer_name')->nullable();
            $table->text('weapon_trainer_desig')->nullable();
            $table->text('weapon_trainer_email')->nullable();
            $table->text('weapon_trainer_cell')->nullable();
            $table->text('weapon_trainer_office')->nullable();
            $table->text('weapon_trainer_rhq')->nullable();
            $table->text('weapon_trainer_region')->nullable();
            $table->text('weapon_trainer_cards')->nullable();
            $table->text('weapon_guards_cards')->nullable();
            //Frisking Procedures
            $table->boolean('frisking_check')->default(false);
            $table->text('frisking_video')->nullable();
            $table->text('frisking_literature')->nullable();
            $table->text('frisking_trainer_name')->nullable();
            $table->text('frisking_trainer_desig')->nullable();
            $table->text('frisking_trainer_email')->nullable();
            $table->text('frisking_trainer_cell')->nullable();
            $table->text('frisking_trainer_office')->nullable();
            $table->text('frisking_trainer_rhq')->nullable();
            $table->text('frisking_trainer_region')->nullable();
            $table->text('frisking_trainer_cards')->nullable();
            $table->text('frisking_guards_cards')->nullable();
            //GateHouse Management System
            $table->boolean('gatehouse_check')->default(false);
            $table->text('gatehouse_video')->nullable();
            $table->text('gatehouse_literature')->nullable();
            $table->text('gatehouse_trainer_name')->nullable();
            $table->text('gatehouse_trainer_desig')->nullable();
            $table->text('gatehouse_trainer_email')->nullable();
            $table->text('gatehouse_trainer_cell')->nullable();
            $table->text('gatehouse_trainer_office')->nullable();
            $table->text('gatehouse_trainer_rhq')->nullable();
            $table->text('gatehouse_trainer_region')->nullable();
            $table->text('gatehouse_trainer_cards')->nullable();
            $table->text('gatehouse_guards_cards')->nullable();
            //OPtimum Use of Security Equipments
            $table->boolean('optimum_check')->default(false);
            $table->text('optimum_video')->nullable();
            $table->text('optimum_literature')->nullable();
            $table->text('optimum_trainer_name')->nullable();
            $table->text('optimum_trainer_desig')->nullable();
            $table->text('optimum_trainer_email')->nullable();
            $table->text('optimum_trainer_cell')->nullable();
            $table->text('optimum_trainer_office')->nullable();
            $table->text('optimum_trainer_rhq')->nullable();
            $table->text('optimum_trainer_region')->nullable();
            $table->text('optimum_trainer_cards')->nullable();
            $table->text('optimum_guards_cards')->nullable();
            //Radio Communication & Survillence
            $table->boolean('radio_check')->default(false);
            $table->text('radio_video')->nullable();
            $table->text('radio_literature')->nullable();
            $table->text('radio_trainer_name')->nullable();
            $table->text('radio_trainer_desig')->nullable();
            $table->text('radio_trainer_email')->nullable();
            $table->text('radio_trainer_cell')->nullable();
            $table->text('radio_trainer_office')->nullable();
            $table->text('radio_trainer_rhq')->nullable();
            $table->text('radio_trainer_region')->nullable();
            $table->text('radio_trainer_cards')->nullable();
            $table->text('radio_guards_cards')->nullable();
            //First Aid & Rescue Techniques
            $table->boolean('aid_check')->default(false);
            $table->text('firstaid_video')->nullable();
            $table->text('firstaid_literature')->nullable();
            $table->text('firstaid_trainer_name')->nullable();
            $table->text('firstaid_trainer_desig')->nullable();
            $table->text('firstaid_trainer_email')->nullable();
            $table->text('firstaid_trainer_cell')->nullable();
            $table->text('firstaid_trainer_office')->nullable();
            $table->text('firstaid_trainer_rhq')->nullable();
            $table->text('firstaid_trainer_region')->nullable();
            $table->text('firstaid_trainer_cards')->nullable();
            $table->text('firstaid_guards_cards')->nullable();
            //Fire Fighting & Damage Control
            $table->boolean('fire_check')->default(false);
            $table->text('fire_video')->nullable();
            $table->text('fire_literature')->nullable();
            $table->text('fire_trainer_name')->nullable();
            $table->text('fire_trainer_desig')->nullable();
            $table->text('fire_trainer_email')->nullable();
            $table->text('fire_trainer_cell')->nullable();
            $table->text('fire_trainer_office')->nullable();
            $table->text('fire_trainer_rhq')->nullable();
            $table->text('fire_trainer_region')->nullable();
            $table->text('fire_trainer_cards')->nullable();
            $table->text('fire_guards_cards')->nullable();
            //Self Defense Techniques
            $table->boolean('self_check')->default(false);
            $table->text('self_video')->nullable();
            $table->text('self_literature')->nullable();
            $table->text('self_trainer_name')->nullable();
            $table->text('self_trainer_desig')->nullable();
            $table->text('self_trainer_email')->nullable();
            $table->text('self_trainer_cell')->nullable();
            $table->text('self_trainer_office')->nullable();
            $table->text('self_trainer_rhq')->nullable();
            $table->text('self_trainer_region')->nullable();
            $table->text('self_trainer_cards')->nullable();
            $table->text('self_guards_cards')->nullable();
            //Close Quater Battle
            $table->boolean('close_check')->default(false);
            $table->text('close_video')->nullable();
            $table->text('close_literature')->nullable();
            $table->text('close_trainer_name')->nullable();
            $table->text('close_trainer_desig')->nullable();
            $table->text('close_trainer_email')->nullable();
            $table->text('close_trainer_cell')->nullable();
            $table->text('close_trainer_office')->nullable();
            $table->text('close_trainer_rhq')->nullable();
            $table->text('close_trainer_region')->nullable();
            $table->text('close_trainer_cards')->nullable();
            $table->text('close_guards_cards')->nullable();
            //Facility Management
            $table->boolean('first_aid_check')->default(false);
            $table->text('first_aid_quantity')->nullable();
            $table->boolean('umbrella_check')->default(false);
            $table->text('umbrella_quantity')->nullable();
            $table->boolean('wireless_check')->default(false);
            $table->text('wireless_quantity')->nullable();
            $table->boolean('mega_check')->default(false);
            $table->text('mega_phone_quantity')->nullable();
            $table->boolean('sofa_check')->default(false);
            $table->text('sofas_quantity')->nullable();
            $table->boolean('water_check')->default(false);
            $table->text('watercooler_quantity')->nullable();
            $table->text('media_attach')->nullable();
            $table->longText('media_notes')->nullable();
            //Nearest Hospital
            $table->text('nearest_hospital')->nullable();
            $table->text('hospital_area')->nullable();
            $table->text('hospital_city')->nullable();
            $table->text('hospital_gps')->nullable();
            $table->text('hospital_pic')->nullable();
            //Findings
            $table->text('incident_attach')->nullable();
            $table->longText('incident_notes')->nullable();
            $table->text('suggestion_attach')->nullable();
            $table->longText('suggestion_notes')->nullable();
            $table->text('observation_attach')->nullable();
            $table->longText('observation_notes')->nullable();
            $table->text('remarks_attach')->nullable();
            $table->longText('remarks_notes')->nullable();
            //Training Range
            $table->text('t_range_name')->nullable();
            $table->text('t_range_desig')->nullable();
            $table->text('t_range_dept')->nullable();
            $table->text('t_range_cell')->nullable();
            $table->text('t_range_email')->nullable();
            $table->text('t_range_front')->nullable();
            $table->text('t_range_back')->nullable();
            $table->text('t_range_office')->nullable();
            $table->text('t_range_building')->nullable();
            $table->text('t_range_block')->nullable();
            $table->text('t_range_area')->nullable();
            $table->text('t_range_city')->nullable();
            $table->text('t_range_photo')->nullable();
            $table->text('adress_range_email')->nullable();
            $table->text('t_range_web')->nullable();
            $table->text('t_range_pin')->nullable();
            $table->text('t_range_gps')->nullable();
            //Checklist
            $table->boolean('point_one_check')->default(false);
            $table->text('point_one')->nullable();
            $table->boolean('point_two_check')->default(false);
            $table->text('point_two')->nullable();
            $table->boolean('point_three_check')->default(false);
            $table->text('point_three')->nullable();
            $table->boolean('point_four_check')->default(false);
            $table->text('point_four')->nullable();
            $table->boolean('point_five_check')->default(false);
            $table->text('point_five')->nullable();
            $table->boolean('point_six_check')->default(false);
            $table->text('point_six')->nullable();
            $table->boolean('point_seven_check')->default(false);
            $table->text('point_seven')->nullable();
            $table->boolean('point_eight_check')->default(false);
            $table->text('point_eight')->nullable();
            $table->boolean('point_nine_check')->default(false);
            $table->text('point_nine')->nullable();
            $table->boolean('point_ten_check')->default(false);
            $table->text('point_ten')->nullable();
            $table->boolean('point_eleven_check')->default(false);
            $table->text('point_eleven')->nullable();
            $table->boolean('point_twelve_check')->default(false);
            $table->text('point_twelve')->nullable();
            $table->boolean('point_thirteen_check')->default(false);
            $table->text('point_thirteen')->nullable();
            $table->boolean('point_forteen_check')->default(false);
            $table->text('point_forteen')->nullable();
            $table->boolean('point_fifteen_check')->default(false);
            $table->text('point_fifteen')->nullable();
            $table->boolean('point_sixteen_check')->default(false);
            $table->text('point_sixteen')->nullable();
            $table->boolean('point_seventeen_check')->default(false);
            $table->text('point_seventeen')->nullable();
            $table->boolean('point_eighteen_check')->default(false);
            $table->text('point_eighteen')->nullable();
            $table->boolean('point_ninteen_check')->default(false);
            $table->text('point_ninteen')->nullable();
            $table->boolean('point_twenty_check')->default(false);
            $table->text('point_twenty')->nullable();
            $table->boolean('point_twentyone_check')->default(false);
            $table->text('point_twentyone')->nullable();
            $table->boolean('point_twentytwo_check')->default(false);
            $table->text('point_twentytwo')->nullable();
            $table->boolean('point_twentythree_check')->default(false);
            $table->text('point_twentythree')->nullable();
            $table->boolean('point_twentyfour_check')->default(false);
            $table->text('point_twentyfour')->nullable();
            $table->boolean('point_twentyfive_check')->default(false);
            $table->text('point_twentyfive')->nullable();
            $table->boolean('point_twentysix_check')->default(false);
            $table->text('point_twentysix')->nullable();

            $table->timestamps();
        });

    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('trainings');
    }
};
