<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void
    {
        Schema::create('employee_salary_slips', function (Blueprint $table) {
            $table->id();

            // Payroll identity
            $table->string('payroll_month', 7); // YYYY-MM
            $table->date('dated')->nullable();

            // Salary rates
            $table->decimal('basic_salary', 12, 2)->default(0);
            $table->decimal('per_day', 10, 2)->default(0);
            $table->decimal('per_hour', 10, 2)->default(0);
            $table->decimal('per_minute', 10, 4)->default(0);

            // Attendance
            $table->integer('salaried_days')->default(0);
            $table->integer('leaves')->default(0);
            $table->integer('absents')->default(0);
            $table->integer('half_days')->default(0);

            // Attendance deductions
            $table->decimal('days_deduction', 12, 2)->default(0);
            $table->decimal('absent_deduction', 12, 2)->default(0);
            $table->decimal('half_day_deduction', 12, 2)->default(0);
            $table->decimal('sandwich_rule_deduction', 12, 2)->default(0);

            // Late & overtime
            $table->integer('late_minutes')->default(0);
            $table->decimal('late_minutes_deduction', 12, 2)->default(0);
            $table->decimal('over_time_hours', 8, 2)->default(0);
            $table->decimal('over_time_pay', 12, 2)->default(0);
            $table->string('over_time_pay_status')->nullable();

            // Deductions
            $table->decimal('advance', 12, 2)->default(0);
            $table->decimal('loan', 12, 2)->default(0);
            $table->decimal('electricity', 12, 2)->default(0);
            $table->decimal('income_tax', 12, 2)->default(0);
            $table->decimal('tax_deduction', 12, 2)->default(0);
            $table->decimal('other_deduction', 12, 2)->default(0);

            // Compensation & totals
            $table->decimal('deduction_before_compensation', 12, 2)->default(0);
            $table->decimal('compensation', 12, 2)->default(0);
            $table->decimal('deduction_after_compensation', 12, 2)->default(0);
            $table->decimal('total_deduction', 12, 2)->default(0);

            // Bonuses & increments
            $table->decimal('bouns', 12, 2)->default(0);
            $table->decimal('totalIncrement', 12, 2)->default(0);

            // Final salary
            $table->decimal('total_salary', 12, 2)->default(0);
            $table->decimal('net_salary', 12, 2)->default(0);
            $table->decimal('approved_salary', 12, 2)->default(0);

            // Relations
            $table->unsignedBigInteger('employee_id');
            $table->unsignedBigInteger('user_id')->nullable(); // generated by

            $table->softDeletes();
            $table->timestamps();

            // Constraints
            $table->unique(['employee_id', 'payroll_month']);
            $table->index('employee_id');
            $table->index('payroll_month');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('employee_salary_slips');
    }
};
