<?php

namespace App\Imports;
use App\Models\Customer;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class CustomersImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
        $customer = Customer::updateOrCreate(
            ['customers_id' => $row['customers_id']],
            [
                'customers_activation_check' => $row['customers_activation_check'] ?? null,
                'qrcode_path' => $row['qrcode_path'] ?? null,
                'customers_name' => $row['customers_name'] ?? null,
                'customers_suffix' => $row['customers_suffix'] ?? null,
                'city_of_deployment' => $row['city_of_deployment'] ?? null,
                'customers_region' => $row['customers_region'] ?? null,
                'branch_name' => $row['branch_name'] ?? null,
                'display_name_as' => $row['display_name_as'] ?? null,
                'nature_of_business' => $row['nature_of_business'] ?? null,
                'website' => $row['website'] ?? null,
                'phone' => $row['phone'] ?? null,
                'email' => $row['email'] ?? null,
                'sub_customer' => $row['sub_customer'] ?? null,
                'approved_com' => $row['approved_com'] ?? false,
                'quick_box' => $row['quick_box'] ?? false,
                'eobi' => $row['eobi'] ?? false,
                'social_security' => $row['social_security'] ?? false,
                'grp_life_ins' => $row['grp_life_ins'] ?? false,
                'approved_attach' => $row['approved_attach'] ?? null,
                'quickbooks_attach' => $row['quickbooks_attach'] ?? null,
                'applicable_compliances' => $row['applicable_compliances'] ?? null,
                'sum_apr' => $row['sum_apr'] ?? null,
                'acm_status' => $row['acm_status'] ?? null,
                'meal_detail' => $row['meal_detail'] ?? null,
                'apr_kpi' => $row['apr_kpi'] ?? null,
                'approv_q_s' => $row['approv_q_s'] ?? false,
                'approv_q_s_attach' => $row['approv_q_s_attach'] ?? null,
                'approv_q_c' => $row['approv_q_c'] ?? false,
                'approv_q_c_attach' => $row['approv_q_c_attach'] ?? null,
                'approv_q_cfo' => $row['approv_q_cfo'] ?? false,
                'approv_q_cfo_attach' => $row['approv_q_cfo_attach'] ?? null,
                'c_e_date' => $row['c_e_date'] ?? null,
                'c_end_date' => $row['c_end_date'] ?? null,
                'c_r_date' => $row['c_r_date'] ?? null,
                'c_r_rem' => $row['c_r_rem'] ?? null,
                'sales_dept' => $row['sales_dept'] ?? false,
                'cmd' => $row['cmd'] ?? false,
                'ops_dept' => $row['ops_dept'] ?? false,
                'finance_dept' => $row['finance_dept'] ?? false,
                'directors' => $row['directors'] ?? false,
                'signed_ser' => $row['signed_ser'] ?? false,
                'signed_ser_attach' => $row['signed_ser_attach'] ?? false,
                'com_ins' => $row['com_ins'] ?? false,
                'com_ins_attach' => $row['com_ins_attach'] ?? false,
                'testimonials' => $row['testimonials'] ?? false,
                'testimonials_attach' => $row['testimonials_attach'] ?? false,
                'sales_inc' => $row['sales_inc'] ?? false,
                'sales_inc_attach' => $row['sales_inc_attach'] ?? null,
                'insc_name' => $row['insc_name'] ?? null,
                'insc_date' => $row['insc_date'] ?? null,
                'per_guan' => $row['per_guan'] ?? null,
                'perfom_attach' => $row['perfom_attach'] ?? null,
                'perform_note' => $row['perform_note'] ?? null,
                'pay_terms' => $row['pay_terms'] ?? null,
                'ntn_fbr' => $row['ntn_fbr'] ?? null,
                'poc_name' => $row['poc_name'] ?? null,
                'poc_desig' => $row['poc_desig'] ?? null,
                'poc_cell' => $row['poc_cell'] ?? null,
                'poc_email' => $row['poc_email'] ?? null,
                'poc_bill_c' => $row['poc_bill_c'] ?? null,
                'poc_bill_d' => $row['poc_bill_d'] ?? null,
                'poc_bill_l' => $row['poc_bill_l'] ?? null,
                'poc_office' => $row['poc_office'] ?? null,
                'poc_floor' => $row['poc_floor'] ?? null,
                'poc_building' => $row['poc_building'] ?? null,
                'poc_block' => $row['poc_block'] ?? null,
                'poc_area' => $row['poc_area'] ?? null,
                'poc_city' => $row['poc_city'] ?? null,
                'poc_photo' => $row['poc_photo'] ?? null,
                'poc_pin' => $row['poc_pin'] ?? null,
                'longitude' => $row['longitude'] ?? null,
                'latitude' => $row['latitude'] ?? null,
                'poc_note' => $row['poc_note'] ?? null,
                'poc_attach' => $row['poc_attach'] ?? null,
                'cf_name' => $row['cf_name'] ?? null,
                'cf_desig' => $row['cf_desig'] ?? null,
                'cf_no' => $row['cf_no'] ?? null,
                'cf_email' => $row['cf_email'] ?? null,
                'cf_office' => $row['cf_office'] ?? null,
                'cf_floor' => $row['cf_floor'] ?? null,
                'cf_building' => $row['cf_building'] ?? null,
                'cf_block' => $row['cf_block'] ?? null,
                'cf_area' => $row['cf_area'] ?? null,
                'cf_city' => $row['cf_city'] ?? null,
                'cf_photo' => $row['cf_photo'] ?? null,
                'cf_pin' => $row['cf_pin'] ?? null,
                'longitude1' => $row['longitude1'] ?? null,
                'latitude1' => $row['latitude1'] ?? null,
                'cf_note' => $row['cf_note'] ?? null,
                'cf_attach' => $row['cf_attach'] ?? null,
                'list_curr' => $row['list_curr'] ?? null,
                'fbr' => $row['fbr'] ?? false,
                'pra' => $row['pra'] ?? false,
                'kpra' => $row['kpra'] ?? false,
                'srb' => $row['srb'] ?? false,
                'bra' => $row['bra'] ?? false,
                'ajk' => $row['ajk'] ?? false,
                'gb' => $row['gb'] ?? false,
                'currency_attach' => $row['currency_attach'] ?? null,
                'currency_note' => $row['currency_note'] ?? null,
                'pat_name' => $row['pat_name'] ?? null,
                'pat_model' => $row['pat_model'] ?? null,
                'pat_make' => $row['pat_make'] ?? null,
                'pat_reg' => $row['pat_reg'] ?? null,
                'pat_quan' => $row['pat_quan'] ?? null,
                'pat_price' => $row['pat_price'] ?? null,
                'pat_val' => $row['pat_val'] ?? null,
                'meeting_date' => $row['meeting_date'] ?? null,
                'meeting_chaired' => $row['meeting_chaired'] ?? null,
                'meeting_minutes' => $row['meeting_minutes'] ?? null,
                'meeting_attach' => $row['meeting_attach'] ?? null,
                'meeting_comment' => $row['meeting_comment'] ?? null,
                'meeting_main_point' => $row['meeting_main_point'] ?? null,
                'meeting_ex_attach' => $row['meeting_ex_attach'] ?? null,
                'meeting_freq' => $row['meeting_freq'] ?? null,
                'meeting_freq_attach' => $row['meeting_freq_attach'] ?? null,
                'meeting_freq_note' => $row['meeting_freq_note'] ?? null,
                'meeting_freq_alert' => $row['meeting_freq_alert'] ?? null,
                'meeting_alert_attach' => $row['meeting_alert_attach'] ?? null,
                'meeting_alert_notes' => $row['meeting_alert_notes'] ?? null,
                'scr_cus_name' => $row['scr_cus_name'] ?? null,
                'scr_cus_region' => $row['scr_cus_region'] ?? null,
                'scr_cus_id' => $row['scr_cus_id'] ?? null,
                'scr_cus_site_id' => $row['scr_cus_site_id'] ?? null,
                'scr_cus_report' => $row['scr_cus_report'] ?? null,
                'scr_cus_date' => $row['scr_cus_date'] ?? null,
                'cus_poc_name' => $row['cus_poc_name'] ?? null,
                'cus_poc_signature' => $row['cus_poc_signature'] ?? null,
                'cus_poc_cell' => $row['cus_poc_cell'] ?? null,
                'cro_name' => $row['cro_name'] ?? null,
                'cro_signature' => $row['cro_signature'] ?? null,
                'cro_cell' => $row['cro_cell'] ?? null,
                'gm_name' => $row['gm_name'] ?? null,
                'gm_signature' => $row['gm_signature'] ?? null,
                'gm_cell' => $row['gm_cell'] ?? null,
                'marks1_schf' => $row['marks1_schf'] ?? null,
                'marks1_rsv' => $row['marks1_rsv'] ?? null,
                'marks1_rsgc' => $row['marks1_rsgc'] ?? null,
                'marks1_cd' => $row['marks1_cd'] ?? null,
                'marks1_tm1' => $row['marks1_tm1'] ?? null,
                'marks2_us' => $row['marks2_us'] ?? null,
                'marks2_tm2' => $row['marks2_tm2'] ?? null,
                'marks3_wfds' => $row['marks3_wfds'] ?? null,
                'marks3_av' => $row['marks3_av'] ?? null,
                'marks3_tm3' => $row['marks3_tm3'] ?? null,
                'marks4_elfat' => $row['marks4_elfat'] ?? null,
                'marks4_athb' => $row['marks4_athb'] ?? null,
                'marks4_tm4' => $row['marks4_tm4'] ?? null,
                'marks5_apapc' => $row['marks5_apapc'] ?? null,
                'marks5_gs' => $row['marks5_gs'] ?? null,
                'marks5_finance' => $row['marks5_finance'] ?? null,
                'marks5_tm5' => $row['marks5_tm5'] ?? null,
                'marks6_sff' => $row['marks6_sff'] ?? null,
                'marks6_tm6' => $row['marks6_tm6'] ?? null,
                'marks7_mvtm' => $row['marks7_mvtm'] ?? null,
                'marks7_mprs' => $row['marks7_mprs'] ?? null,
                'marks7_srlms' => $row['marks7_srlms'] ?? null,
                'marks7_risite' => $row['marks7_risite'] ?? null,
                'marks7_risurr' => $row['marks7_risurr'] ?? null,
                'marks7_sdnl' => $row['marks7_sdnl'] ?? null,
                'marks7_tm7' => $row['marks7_tm7'] ?? null,
                'marks_grand_total' => $row['marks_grand_total'] ?? null,
                'visit_perf_by' => $row['visit_perf_by'] ?? null,
                'pat_super_loc' => $row['pat_super_loc'] ?? null,
                'pat_super_date' => $row['pat_super_date'] ?? null,
                'pat_super_day' => $row['pat_super_day'] ?? null,
                'pat_super_times' => $row['pat_super_times'] ?? null,
                'pat_super_photo' => $row['pat_super_photo'] ?? null,
                'pat_super_video' => $row['pat_super_video'] ?? null,
                'pat_super_inform_email' => $row['pat_super_inform_email'] ?? null,
            ]
        );

        // Update or create related models with null values if not present
        if ($customer) {
            $customer->customersignatories()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'signatory_name' => $row['signatory_name'] ?? null,
                    'signatory_email' => $row['signatory_email'] ?? null,
                    'sign_cell' => $row['sign_cell'] ?? null,
                    'sign_desig' => $row['sign_desig'] ?? null,
                ]
            );

            $customer->customersalary()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'cat_name' => $row['cat_name'] ?? null,
                    'sal_cat' => $row['sal_cat'] ?? null,
                    'sal_days' => $row['sal_days'] ?? null,
                    'leaves_a' => $row['leaves_a'] ?? null,
                    'other_ben' => $row['other_ben'] ?? null,
                    'sal_attach' => $row['sal_attach'] ?? null,
                    'sal_note' => $row['sal_note'] ?? null,
                ]
            );

            $customer->customermanpowers()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'man_post' => $row['man_post'] ?? null,
                    'man_cat' => $row['man_cat'] ?? null,
                    'man_uni' => $row['man_uni'] ?? null,
                    'man_uni_no' => $row['man_uni_no'] ?? null,
                    'man_weapon' => $row['man_weapon'] ?? null,
                    'man_ammu' => $row['man_ammu'] ?? null,
                    'man_equip' => $row['man_equip'] ?? null,
                    'man_equip_attach' => $row['man_equip_attach'] ?? null,
                    's_start_date' => $row['s_start_date'] ?? null,
                    's_end_date' => $row['s_end_date'] ?? null,
                    's_start_time' => $row['s_start_time'] ?? null,
                    's_end_time' => $row['s_end_time'] ?? null,
                    'man_start_date' => $row['man_start_date'] ?? null,
                    'man_end_date' => $row['man_end_date'] ?? null,
                    'man_start_time' => $row['man_start_time'] ?? null,
                    'man_end_time' => $row['man_end_time'] ?? null,
                    'man_quan' => $row['man_quan'] ?? null,
                    'man_hours' => $row['man_hours'] ?? null,
                    'man_jd_attach' => $row['man_jd_attach'] ?? null,
                    'man_any_sp' => $row['man_any_sp'] ?? null,
                    'man_apr_l' => $row['man_apr_l'] ?? null,
                    'man_salary' => $row['man_salary'] ?? null,
                ]
            );

            $customer->customeremergencies()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'emer_ser' => $row['emer_ser'] ?? null,
                    'emer_pic' => $row['emer_pic'] ?? null,
                    'emer_poc_name' => $row['emer_poc_name'] ?? null,
                    'emer_poc_desig' => $row['emer_poc_desig'] ?? null,
                    'emer_poc_cell' => $row['emer_poc_cell'] ?? null,
                    'emer_poc_email' => $row['emer_poc_email'] ?? null,
                    'emer_poc_notes' => $row['emer_poc_notes'] ?? null,
                    'emer_poc_attach' => $row['emer_poc_attach'] ?? null,
                    'emer_office' => $row['emer_office'] ?? null,
                    'emer_floor' => $row['emer_floor'] ?? null,
                    'emer_building' => $row['emer_building'] ?? null,
                    'emer_block' => $row['emer_block'] ?? null,
                    'emer_area' => $row['emer_area'] ?? null,
                    'emer_city' => $row['emer_city'] ?? null,
                    'emer_loc' => $row['emer_loc'] ?? null,
                    'emer_email' => $row['emer_email'] ?? null,
                    'emer_web' => $row['emer_web'] ?? null,
                    'emer_pin' => $row['emer_pin'] ?? null,
                    'longitude2' => $row['longitude2'] ?? null,
                    'latitude2' => $row['latitude2'] ?? null,
                    'emer_app_rental' => $row['emer_app_rental'] ?? null,
                    'emer_attach' => $row['emer_attach'] ?? null,
                    'emer_note' => $row['emer_note'] ?? null,
                ]
            );

            $customer->customerdepartments()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'dept_type' => $row['dept_type'] ?? null,
                    'dept_name' => $row['dept_name'] ?? null,
                    'dept_email' => $row['dept_email'] ?? null,
                    'dept_cell' => $row['dept_cell'] ?? null,
                    'dept_address' => $row['dept_address'] ?? null,
                    'dept_desig' => $row['dept_desig'] ?? null,
                    'dept_front' => $row['dept_front'] ?? null,
                    'dept_back' => $row['dept_back'] ?? null,
                    'dept_notes' => $row['dept_notes'] ?? null,
                    'dept_attach' => $row['dept_attach'] ?? null,
                    'dept_office' => $row['dept_office'] ?? null,
                    'dept_floor' => $row['dept_floor'] ?? null,
                    'dept_build' => $row['dept_build'] ?? null,
                    'dept_block' => $row['dept_block'] ?? null,
                    'dept_area' => $row['dept_area'] ?? null,
                    'dept_city' => $row['dept_city'] ?? null,
                    'dept_photo' => $row['dept_photo'] ?? null,
                    'dept_pin' => $row['dept_pin'] ?? null,
                    'dept_ex_notes' => $row['dept_ex_notes'] ?? null,
                    'dept_ex_attach' => $row['dept_ex_attach'] ?? null,
                ]
            );

            $customer->customerinspections()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'inspection_no' => $row['inspection_no'] ?? null,
                    'inspection_emp_id' => $row['inspection_emp_id'] ?? null,
                    'inspection_emp_name' => $row['inspection_emp_name'] ?? null,
                    'inspection_emp_cell' => $row['inspection_emp_cell'] ?? null,
                    'inspection_emp_dept' => $row['inspection_emp_dept'] ?? null,
                    'inspection_date' => $row['inspection_date'] ?? null,
                    'inspection_pic' => $row['inspection_pic'] ?? null,
                    'inspection_rem_petr' => $row['inspection_rem_petr'] ?? null,
                    'inspection_note' => $row['inspection_note'] ?? null,
                    'inspection_attach' => $row['inspection_attach'] ?? null,
                ]
            );

            $customer->customerarmourers()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'arm_branch_name' => $row['arm_branch_name'] ?? null,
                    'arm_branch_id' => $row['arm_branch_id'] ?? null,
                    'arm_site_id' => $row['arm_site_id'] ?? null,
                    'arm_client_name' => $row['arm_client_name'] ?? null,
                    'arm_weapon_no' => $row['arm_weapon_no'] ?? null,
                    'arm_weapon_bore' => $row['arm_weapon_bore'] ?? null,
                    'arm_weapon_type' => $row['arm_weapon_type'] ?? null,
                    'arm_work_detail' => $row['arm_work_detail'] ?? null,
                    'arm_sign_cus' => $row['arm_sign_cus'] ?? null,
                    'arm_auth' => $row['arm_auth'] ?? null,
                    'arm_auth_no' => $row['arm_auth_no'] ?? null,
                    'arm_auth_date' => $row['arm_auth_date'] ?? null,
                    'arm_auth_issue' => $row['arm_auth_issue'] ?? null,
                    'arm_weapon_cleaned' => $row['arm_weapon_cleaned'] ?? null,
                    'type_weapon_cleaned' => $row['type_weapon_cleaned'] ?? null,
                    'arm_pic_b' => $row['arm_pic_b'] ?? null,
                    'arm_pic_a' => $row['arm_pic_a'] ?? null,
                    'arm_cost_day' => $row['arm_cost_day'] ?? null,
                    'arm_cost_bill' => $row['arm_cost_bill'] ?? null,
                    'arm_next_clean' => $row['arm_next_clean'] ?? null,
                    'arm_auth_notes' => $row['arm_auth_notes'] ?? null,
                    'arm_auth_attach' => $row['arm_auth_attach'] ?? null,
                ]
            );

            $customer->customerincidents()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'client_name' => $row['client_name'] ?? null,
                    'client_id' => $row['client_id'] ?? null,
                    'client_site_id' => $row['client_site_id'] ?? null,
                    'client_poc' => $row['client_poc'] ?? null,
                    'client_cell' => $row['client_cell'] ?? null,
                    'client_email' => $row['client_email'] ?? null,
                    'client_site_address' => $row['client_site_address'] ?? null,
                    'client_office' => $row['client_office'] ?? null,
                    'client_build' => $row['client_build'] ?? null,
                    'client_street' => $row['client_street'] ?? null,
                    'client_area' => $row['client_area'] ?? null,
                    'client_city' => $row['client_city'] ?? null,
                    'client_fir' => $row['client_fir'] ?? null,
                    'arrest' => $row['arrest'] ?? null,
                    'casual' => $row['casual'] ?? null,
                    'injuired' => $row['injuired'] ?? null,
                    'incident_rep' => $row['incident_rep'] ?? null,
                    'police_officer_name' => $row['police_officer_name'] ?? null,
                    'station' => $row['station'] ?? null,
                    'rank' => $row['rank'] ?? null,
                    'report_made_by' => $row['report_made_by'] ?? null,
                    'report_date' => $row['report_date'] ?? null,
                    'report_time' => $row['report_time'] ?? null,
                    'report_apr_by' => $row['report_apr_by'] ?? null,
                    'report_shared' => $row['report_shared'] ?? null,
                    'incident_type' => $row['incident_type'] ?? null,
                    'weapon_used' => $row['weapon_used'] ?? null,
                    'detail_of_attacker' => $row['detail_of_attacker'] ?? null,
                    'attacker_desc' => $row['attacker_desc'] ?? null,
                    'attacker_shoe' => $row['attacker_shoe'] ?? null,
                    'attacker_beard' => $row['attacker_beard'] ?? null,
                    'attacker_lang' => $row['attacker_lang'] ?? null,
                    'focused' => $row['focused'] ?? null,
                    'opening_phrase' => $row['opening_phrase'] ?? null,
                    'any_usual' => $row['any_usual'] ?? null,
                    'estimated_loss' => $row['estimated_loss'] ?? null,
                    'desc_loss' => $row['desc_loss'] ?? null,
                    'officer_response' => $row['officer_response'] ?? null,
                    'incident_attach' => $row['incident_attach'] ?? null,
                    'incident_note' => $row['incident_note'] ?? null,
                ]
            );

            $customer->customerassigments()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'asig_customer_name' => $row['asig_customer_name'] ?? null,
                    'task_assigning' => $row['task_assigning'] ?? null,
                    'asig_desig' => $row['asig_desig'] ?? null,
                    'asig_office' => $row['asig_office'] ?? null,
                    'asig_building' => $row['asig_building'] ?? null,
                    'asig_road' => $row['asig_road'] ?? null,
                    'asig_area' => $row['asig_area'] ?? null,
                    'asig_city' => $row['asig_city'] ?? null,
                    'asig_country' => $row['asig_country'] ?? null,
                    'asig_security' => $row['asig_security'] ?? null,
                    'asig_contact' => $row['asig_contact'] ?? null,
                    'incharge_name' => $row['incharge_name'] ?? null,
                    'incharge_desig' => $row['incharge_desig'] ?? null,
                    'incharge_contact' => $row['incharge_contact'] ?? null,
                    'incharge_help' => $row['incharge_help'] ?? null,
                    'incharge_desc' => $row['incharge_desc'] ?? null,
                    'incharge_risk' => $row['incharge_risk'] ?? null,
                    'incharge_asig' => $row['incharge_asig'] ?? null,
                    'incharge_signed_by' => $row['incharge_signed_by'] ?? null,
                    'incharge_date' => $row['incharge_date'] ?? null,
                    'incharge_offc' => $row['incharge_offc'] ?? null,
                    'incharge_floor' => $row['incharge_floor'] ?? null,
                    'incharge_build' => $row['incharge_build'] ?? null,
                    'incharge_block' => $row['incharge_block'] ?? null,
                    'incharge_area' => $row['incharge_area'] ?? null,
                    'incharge_city' => $row['incharge_city'] ?? null,
                    'incharge_pin' => $row['incharge_pin'] ?? null,
                    'longitude4' => $row['longitude4'] ?? null,
                    'latitude4' => $row['latitude4'] ?? null,
                    'incharge_country' => $row['incharge_country'] ?? null,
                    'incharge_site' => $row['incharge_site'] ?? null,
                    'incharge_a_g' => $row['incharge_a_g'] ?? null,
                    'incharge_a_ung' => $row['incharge_a_ung'] ?? null,
                    'incharge_t_g' => $row['incharge_t_g'] ?? null,
                    'rec_inc_rel' => $row['rec_inc_rel'] ?? null,
                    'feq_occ' => $row['feq_occ'] ?? null,
                    'exp_piff' => $row['exp_piff'] ?? null,
                    'any_spec' => $row['any_spec'] ?? null,
                    'petr_instruc' => $row['petr_instruc'] ?? null,
                    'asig_ex_attach' => $row['asig_ex_attach'] ?? null,
                    'asig_ex_notes' => $row['asig_ex_notes'] ?? null,
                ]
            );

            $customer->customeraudits()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'audit_file' => $row['audit_file'] ?? null,
                    'audit_sign' => $row['audit_sign'] ?? null,
                    'audit_date' => $row['audit_date'] ?? null,
                    'audit_attach' => $row['audit_attach'] ?? null,
                    'audit_checked_by' => $row['audit_checked_by'] ?? null,
                    'audit_ex_attach' => $row['audit_ex_attach'] ?? null,
                    'audit_note' => $row['audit_note'] ?? null,
                ]

            );

            $customer->customerbussinesses()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'cb_name' => $row['cb_name'] ?? null,
                    'cb_desig' => $row['cb_desig'] ?? null,
                    'cb_comp_name' => $row['cb_comp_name'] ?? null,
                    'cb_email' => $row['cb_email'] ?? null,
                    'cb_cno' => $row['cb_cno'] ?? null,
                    'bussiness_name' => $row['bussiness_name'] ?? null,
                    'bussiness_nature' => $row['bussiness_nature'] ?? null,
                    'bussiness_office_no' => $row['bussiness_office_no'] ?? null,
                    'bussiness_floor' => $row['bussiness_floor'] ?? null,
                    'bussiness_building' => $row['bussiness_building'] ?? null,
                    'bussiness_block' => $row['bussiness_block'] ?? null,
                    'bussiness_area' => $row['bussiness_area'] ?? null,
                    'bussiness_city' => $row['bussiness_city'] ?? null,
                    'bussiness_photo' => $row['bussiness_photo'] ?? null,
                    'bussiness_email' => $row['bussiness_email'] ?? null,
                    'bussiness_web' => $row['bussiness_web'] ?? null,
                    'bussiness_pin' => $row['bussiness_pin'] ?? null,
                    'longitude5' => $row['longitude5'] ?? null,
                    'latitude5' => $row['latitude5'] ?? null,
                    'bussiness_notes' => $row['bussiness_notes'] ?? null,
                    'bussiness_attach' => $row['bussiness_attach'] ?? null,
                ]
            );

            $customer->customeractivities()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'promotional_act' => $row['promotional_act'] ?? null,
                    'promotional_quantity' => $row['promotional_quantity'] ?? null,
                    'prom_price' => $row['prom_price'] ?? null,
                    'prom_date' => $row['prom_date'] ?? null,
                    'promotional_notes' => $row['promotional_notes'] ?? null,
                    'promotional_attach' => $row['promotional_attach'] ?? null,
                ]
            );

            $customer->customerfeedbacks()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'feed_client_name' => $row['feed_client_name'] ?? null,
                    'feed_client_poc_name' => $row['feed_client_poc_name'] ?? null,
                    'feed_client_email' => $row['feed_client_email'] ?? null,
                    'feed_client_id' => $row['feed_client_id'] ?? null,
                    'feed_client_site_id' => $row['feed_client_site_id'] ?? null,
                    'feed_desig' => $row['feed_desig'] ?? null,
                    'feed_cell' => $row['feed_cell'] ?? null,
                    'feed_month' => $row['feed_month'] ?? null,
                    'q1' => $row['q1'] ?? null,
                    'q2' => $row['q2'] ?? null,
                    'q3' => $row['q3'] ?? null,
                    'q4' => $row['q4'] ?? null,
                    'q5' => $row['q5'] ?? null,
                    'q6' => $row['q6'] ?? null,
                    'q7' => $row['q7'] ?? null,
                    'q8' => $row['q8'] ?? null,
                    'q9' => $row['q9'] ?? null,
                    'q10' => $row['q10'] ?? null,
                    'total_score' => $row['total_score'] ?? null,
                    'feed_company_name' => $row['feed_company_name'] ?? null,
                    'feed_poc_name' => $row['feed_poc_name'] ?? null,
                    'feed_comment' => $row['feed_comment'] ?? null,
                    'feedback_form' => $row['feedback_form'] ?? null,
                    'feed_email' => $row['feed_email'] ?? null,
                    'feed_telephone' => $row['feed_telephone'] ?? null,
                    'feed_signature' => $row['feed_signature'] ?? null,
                    'feed_received' => $row['feed_received'] ?? null,
                    'feed_remarks' => $row['feed_remarks'] ?? null,
                    'feed_attach' => $row['feed_attach'] ?? null,
                ]
            );

            $customer->customercomplaints()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'complaint_no' => $row['complaint_no'] ?? null,
                    'complaint_guards_duty' => $row['complaint_guards_duty'] ?? null,
                    'complaint_gaurd_note' => $row['complaint_gaurd_note'] ?? null,
                    'complaint_guard_attach' => $row['complaint_guard_attach'] ?? null,
                    'wea_uni_equip' => $row['wea_uni_equip'] ?? null,
                    'wue_note' => $row['wue_note'] ?? null,
                    'finance_dept' => $row['finance_dept'] ?? null,
                    'fd_note' => $row['fd_note'] ?? null,
                    'fd_attach' => $row['fd_attach'] ?? null,
                    'src_complaint' => $row['src_complaint'] ?? null,
                    'src_note' => $row['src_note'] ?? null,
                    'src_attach' => $row['src_attach'] ?? null,
                    'mng_feed' => $row['mng_feed'] ?? null,
                    'mng_attach' => $row['mng_attach'] ?? null,
                    'mng_note' => $row['mng_note'] ?? null,
                    'complaint_poc_name' => $row['complaint_poc_name'] ?? null,
                    'complaint_poc_desig' => $row['complaint_poc_desig'] ?? null,
                    'complaint_poc_dept' => $row['complaint_poc_dept'] ?? null,
                    'complaint_poc_email' => $row['complaint_poc_email'] ?? null,
                    'complaint_poc_contact' => $row['complaint_poc_contact'] ?? null,
                    'complaint_picture' => $row['complaint_picture'] ?? null,
                    'details_complaint' => $row['details_complaint'] ?? null,
                    'details_attach' => $row['details_attach'] ?? null,
                    'complaint_tagged' => $row['complaint_tagged'] ?? null,
                    'complaint_arressed' => $row['complaint_arressed'] ?? null,
                    'complaint_addressed_attach' => $row['complaint_addressed_attach'] ?? null,
                    'complaint_addressed_note' => $row['complaint_addressed_note'] ?? null,
                ]

            );

            $customer->customernotifications()->updateOrCreate(
                ['customers_id' => $customer->id],
                [
                    'notification_no' => $row['notification_no'] ?? null,
                    'notification_related' => $row['notification_related'] ?? null,
                    'notification_attach' => $row['notification_attach'] ?? null,
                    'notification_note' => $row['notification_note'] ?? null,
                    'notification_shared' => $row['notification_shared'] ?? null,
                    'notification_ex_attach' => $row['notification_ex_attach'] ?? null,
                    'notification_ex_note' => $row['notification_ex_note'] ?? null,
                ]
            );
        }

        return $customer;
    }
}
