<?php

namespace App\Imports;

use App\Models\Hrm;
use App\Models\Guarantor;
use App\Models\Work;
use App\Models\Education;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class HrmsImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
          // Clean and validate CNIC
        $cnic = preg_replace('/[^0-9]/', '', $row['cnic'] ?? '');
        $cnic = substr($cnic, 0, 13);
        $cell = preg_replace('/[^0-9]/', '', $row['cell'] ?? '');
        $hrm = Hrm::updateOrCreate(
            ['employee_no' => $row['employee_no']],
            [
                'activation' => $row['activation'] ?? null,
                'name' => $row['name'] ?? null,
                'fname' => $row['fname'] ?? null,
                'cnic' => $row['cnic'] ?? null,
                'employee_no' => $row['employee_no'] ?? null,
                'bank' => $row['bank'] ?? null,
                'bank_account' => $row['bank_account'] ?? null,
                'cell' => $row['cell'] ?? null,
                'photo' => $row['photo'] ?? null,
                'category' => $row['category'] ?? null,
                'rank' => $row['rank'] ?? null,
                'designation' => $row['designation'] ?? null,
                'unit' => $row['unit'] ?? null,
                'hired_at' => $row['hired_at'] ?? null,
                'hrm_region' => $row['hrm_region'] ?? null,
                'hrm_location' => $row['hrm_location'] ?? null,
                'client_id' => $row['client_id'] ?? null,
                'client_name' => $row['client_name'] ?? null,
                'dob' => $row['dob'] ?? null,
                'religion' => $row['religion'] ?? null,
                'caste' => $row['caste'] ?? null,
                'gender' => $row['gender'] ?? null,
                'p_cell' => $row['p_cell'] ?? null,
                'e_cell' => $row['e_cell'] ?? null,
                'blood' => $row['blood'] ?? null,
                'email' => $row['email'] ?? null,
                'cnic_front' => $row['cnic_front'] ?? null,
                'cnic_back' => $row['cnic_back'] ?? null,
                'f_attach' => $row['f_attach'] ?? null,
                'm_status' => $row['m_status'] ?? null,
                'no_of_kids' => $row['no_of_kids'] ?? null,
                'm_kids' => $row['m_kids'] ?? null,
                'f_kids' => $row['f_kids'] ?? null,
                'cnic_issue' => $row['cnic_issue'] ?? null,
                'cnic_expire' => $row['cnic_expire'] ?? null,
                'notes' => $row['notes'] ?? null,
                't_address' => $row['t_address'] ?? null,
                't_area' => $row['t_area'] ?? null,
                't_city' => $row['t_city'] ?? null,
                't_police' => $row['t_police'] ?? null,
                't_district' => $row['t_district'] ?? null,
                't_post' => $row['t_post'] ?? null,
                't_tehsil' => $row['t_tehsil'] ?? null,
                't_province' => $row['t_province'] ?? null,
                't_postal' => $row['t_postal'] ?? null,
                't_residing' => $row['t_residing'] ?? null,
                't_gps' => $row['t_gps'] ?? null,
                't_attach' => $row['t_attach'] ?? null,
                't_note' => $row['t_note'] ?? null,
                'p_address' => $row['p_address'] ?? null,
                'p_area' => $row['p_area'] ?? null,
                'p_city' => $row['p_city'] ?? null,
                'p_police' => $row['p_police'] ?? null,
                'p_district' => $row['p_district'] ?? null,
                'p_post' => $row['p_post'] ?? null,
                'p_tehsil' => $row['p_tehsil'] ?? null,
                'p_province' => $row['p_province'] ?? null,
                'p_postal' => $row['p_postal'] ?? null,
                'p_residing' => $row['p_residing'] ?? null,
                'p_gps' => $row['p_gps'] ?? null,
                'p_attach' => $row['p_attach'] ?? null,
                'p_note' => $row['p_note'] ?? null,
                'nok_name' => $row['nok_name'] ?? null,
                'nok_cnic' => $row['nok_cnic'] ?? null,
                'nok_fname' => $row['nok_fname'] ?? null,
                'nok_relation' => $row['nok_relation'] ?? null,
                'nok_death' => $row['nok_death'] ?? null,
                'nok_frc' => $row['nok_frc'] ?? null,
                'h_verify' => $row['h_verify'] ?? null,
                'b_verify' => $row['b_verify'] ?? null,
                'p_verify' => $row['p_verify'] ?? null,
                'd_book' => $row['d_book'] ?? null,
                'v_verify' => $row['v_verify'] ?? null,
                'copy_bill' => $row['copy_bill'] ?? null,
                'n_verify' => $row['n_verify'] ?? null,
                'insurrance' => $row['insurrance'] ?? null,
                'guard_bank' => $row['guard_bank'] ?? null,
                'bio_verify' => $row['bio_verify'] ?? null,
                'c_verify' => $row['c_verify'] ?? null,
                'dpo_verify' => $row['dpo_verify'] ?? null,
                'form_send' => $row['form_send'] ?? null,
                'sent_on' => $row['sent_on'] ?? null,
                'form_attach' => $row['form_attach'] ?? null,
                'form_rec' => $row['form_rec'] ?? null,
                'rec_on' => $row['rec_on'] ?? null,
                'rec_attach' => $row['rec_attach'] ?? null,
                'eight_verify' => $row['eight_verify'] ?? null,
                'sahulat_v' => $row['sahulat_v'] ?? null,
                'look_back1' => $row['look_back1'] ?? null,
                'frequency1' => $row['frequency1'] ?? null,
                'notes1' => $row['notes1'] ?? null,
                'look_back2' => $row['look_back2'] ?? null,
                'frequency2' => $row['frequency2'] ?? null,
                'notes2' => $row['notes2'] ?? null,
                'look_back3' => $row['look_back3'] ?? null,
                'frequency3' => $row['frequency3'] ?? null,
                'notes3' => $row['notes3'] ?? null,
                'look_back4' => $row['look_back4'] ?? null,
                'frequency4' => $row['frequency4'] ?? null,
                'notes4' => $row['notes4'] ?? null,
                'look_back5' => $row['look_back5'] ?? null,
                'frequency5' => $row['frequency5'] ?? null,
                'notes5' => $row['notes5'] ?? null,
                'look_back6' => $row['look_back6'] ?? null,
                'frequency6' => $row['frequency6'] ?? null,
                'notes6' => $row['notes6'] ?? null,
                'look_back7' => $row['look_back7'] ?? null,
                'frequency7' => $row['frequency7'] ?? null,
                'notes7' => $row['notes7'] ?? null,
                'look_back8' => $row['look_back8'] ?? null,
                'frequency8' => $row['frequency8'] ?? null,
                'notes8' => $row['notes8'] ?? null,
                'look_back9' => $row['look_back9'] ?? null,
                'frequency9' => $row['frequency9'] ?? null,
                'notes9' => $row['notes9'] ?? null,
                'look_back10' => $row['look_back10'] ?? null,
                'frequency10' => $row['frequency10'] ?? null,
                'notes10' => $row['notes10'] ?? null,
                'look_back11' => $row['look_back11'] ?? null,
                'frequency11' => $row['frequency11'] ?? null,
                'notes11' => $row['notes11'] ?? null,
                'look_back12' => $row['look_back12'] ?? null,
                'frequency12' => $row['frequency12'] ?? null,
                'notes12' => $row['notes12'] ?? null,
                'look_back13' => $row['look_back13'] ?? null,
                'frequency13' => $row['frequency13'] ?? null,
                'notes13' => $row['notes13'] ?? null,
                'look_back14' => $row['look_back14'] ?? null,
                'frequency14' => $row['frequency14'] ?? null,
                'notes14' => $row['notes14'] ?? null,
                'l_finger' => $row['l_finger'] ?? null,
                'f_finger' => $row['f_finger'] ?? null,
                'm_finger' => $row['m_finger'] ?? null,
                'i_finger' => $row['i_finger'] ?? null,
                't_finger' => $row['t_finger'] ?? null,
                'additionals' => $row['additionals'] ?? null,
                'f_attachment' => $row['f_attachment'] ?? null,
                'finger_note' => $row['finger_note'] ?? null,
                'h_age' => $row['h_age'] ?? null,
                'weight' => $row['weight'] ?? null,
                'height' => $row['height'] ?? null,
                'complection' => $row['complection'] ?? null,
                'ay_other_d' => $row['ay_other_d'] ?? null,
                'medical_category' => $row['medical_category'] ?? null,
                'vaccine_card' => $row['vaccine_card'] ?? null,
                'medical_fit_card' => $row['medical_fit_card'] ?? null,
                'medical_fit_attach' => $row['medical_fit_attach'] ?? null,
                'medical_fit_note' => $row['medical_fit_note'] ?? null,
                'phy_name' => $row['phy_name'] ?? null,
                'phy_cell' => $row['phy_cell'] ?? null,
                'phy_office' => $row['phy_office'] ?? null,
                'phy_building' => $row['phy_building'] ?? null,
                'phy_block' => $row['phy_block'] ?? null,
                'phy_area' => $row['phy_area'] ?? null,
                'phy_city' => $row['phy_city'] ?? null,
                'phy_loc' => $row['phy_loc'] ?? null,
                'phy_note' => $row['phy_note'] ?? null,
                'phy_attach' => $row['phy_attach'] ?? null,
                'vac_type' => $row['vac_type'] ?? null,
                'vac_pr' => $row['vac_pr'] ?? null,
                'c_eobi' => $row['c_eobi'] ?? null,
                'f_eobi' => $row['f_eobi'] ?? null,
                'sub_eobi' => $row['sub_eobi'] ?? null,
                'front_eobi' => $row['front_eobi'] ?? null,
                'back_eobi' => $row['back_eobi'] ?? null,
                'ss_staff' => $row['ss_staff'] ?? null,
                'fall_ss' => $row['fall_ss'] ?? null,
                'sub_ss' => $row['sub_ss'] ?? null,
                'front_ss' => $row['front_ss'] ?? null,
                'back_ss' => $row['back_ss'] ?? null,
                'gli_ins' => $row['gli_ins'] ?? null,
                'gli_name' => $row['gli_name'] ?? null,
                'gli_policy' => $row['gli_policy'] ?? null,
                'type_ins' => $row['type_ins'] ?? null,
                'sum_gli' => $row['sum_gli'] ?? null,
                'date_ins' => $row['date_ins'] ?? null,
                'snc_pol' => $row['snc_pol'] ?? null,
                'next_name' => $row['next_name'] ?? null,
                'next_cnic' => $row['next_cnic'] ?? null,
                'next_fname' => $row['next_fname'] ?? null,
                'next_relation' => $row['next_relation'] ?? null,
                'next_death' => $row['next_death'] ?? null,
                'next_frc' => $row['next_frc'] ?? null,
                'next_legal' => $row['next_legal'] ?? null,
                'next_photo' => $row['next_photo'] ?? null,
                'next_claim' => $row['next_claim'] ?? null,
                'next_amount' => $row['next_amount'] ?? null,
                'next_check' => $row['next_check'] ?? null,
                'next_date' => $row['next_date'] ?? null,
                'next_copy' => $row['next_copy'] ?? null,
                'next_bank' => $row['next_bank'] ?? null,
                'next_ins' => $row['next_ins'] ?? null,
                'next_attach' => $row['next_attach'] ?? null,
                'ex_next_attach' => $row['ex_next_attach'] ?? null,
                'ex_next_note' => $row['ex_next_note'] ?? null,
                's_license' => $row['s_license'] ?? null,
                's_issuing' => $row['s_issuing'] ?? null,
                's_v_date' => $row['s_v_date'] ?? null,
                's_date' => $row['s_date'] ?? null,
                's_fee' => $row['s_fee'] ?? null,
                's_front' => $row['s_front'] ?? null,
                's_back' => $row['s_back'] ?? null,
                's_notes' => $row['s_notes'] ?? null,
                's_attach' => $row['s_attach'] ?? null,
                'insp_no' => $row['insp_no'] ?? null,
                'insp_name' => $row['insp_name'] ?? null,
                'insp_cell' => $row['insp_cell'] ?? null,
                'insp_date' => $row['insp_date'] ?? null,
                'insp_pic' => $row['insp_pic'] ?? null,
                'rem_petr' => $row['rem_petr'] ?? null,
                'insp_attach' => $row['insp_attach'] ?? null,
                'insp_notes' => $row['insp_notes'] ?? null,
                'observ_mon' => $row['observ_mon'] ?? null,
                'observ_type' => $row['observ_type'] ?? null,
                'hr_remark' => $row['hr_remark'] ?? null,
                'ex_observ_attach' => $row['ex_observ_attach'] ?? null,
                'appraisal' => $row['appraisal'] ?? null,
                'appraisal_attach' => $row['appraisal_attach'] ?? null,
                'appraisal_notes' => $row['appraisal_notes'] ?? null,
            ]
        );

        if ($hrm) {
            $hrm->guarantors()->updateOrCreate(
                ['hrms_id' => $hrm->id],
                [
                    'g_name' => $row['g_name'] ?? null,
                    'g_fname' => $row['g_fname'] ?? null,
                    'g_relation' => $row['g_relation'] ?? null,
                    'g_tenure_rel' => $row['g_tenure_rel'] ?? null,
                    'g_cnic_f' => $row['g_cnic_f'] ?? null,
                    'g_cnic_b' => $row['g_cnic_b'] ?? null,
                    'pos_verify' => $row['pos_verify'] ?? null,
                    'head_office_no' => $row['head_office_no'] ?? null,
                    'head_floor_no' => $row['head_floor_no'] ?? null,
                    'head_building' => $row['head_building'] ?? null,
                    'head_block' => $row['head_block'] ?? null,
                    'head_area' => $row['head_area'] ?? null,
                    'head_city' => $row['head_city'] ?? null,
                    'head_attach' => $row['head_attach'] ?? null,
                ]
            );

            $hrm->workExperiences()->updateOrCreate(
                ['hrms_id' => $hrm->id],
                [
                    'org_name' => $row['org_name'] ?? null,
                    'email_oc' => $row['email_oc'] ?? null,
                    'poc' => $row['poc'] ?? null,
                    'jec' => $row['jec'] ?? null,
                    'jec_attach' => $row['jec_attach'] ?? null,
                    'w_desig' => $row['w_desig'] ?? null,
                    'w_salary' => $row['w_salary'] ?? null,
                    'ser_tenure' => $row['ser_tenure'] ?? null,
                    'ser_other' => $row['ser_other'] ?? null,
                    'achivement' => $row['achivement'] ?? null,
                    'join_date' => $row['join_date'] ?? null,
                    'end_date' => $row['end_date'] ?? null,
                    't_exp' => $row['t_exp'] ?? null,
                ]

            );

            $hrm->education()->updateOrCreate(
                ['hrms_id' => $hrm->id],
                [
                    'degree' => $row['degree'] ?? null,
                    'degree_date' => $row['degree_date'] ?? null,
                    'degree_pic' => $row['degree_pic'] ?? null,
                    'institute_name' => $row['institute_name'] ?? null,
                    'a_body' => $row['a_body'] ?? null,
                    'ex_notes' => $row['ex_notes'] ?? null,
                    'degree_no' => $row['degree_no'] ?? null,
                    'degree_level' => $row['degree_level'] ?? null,
                    'obmarks' => $row['obmarks'] ?? null,
                    't_marks' => $row['t_marks'] ?? null,
                    'grade' => $row['grade'] ?? null,
                    'date_start' => $row['date_start'] ?? null,
                    'date_end' => $row['date_end'] ?? null,
                    'adress_inst' => $row['adress_inst'] ?? null,
                    'deg_attach' => $row['deg_attach'] ?? null,
                ]
            );
        }

        return $hrm;
    }
}


