<?php

namespace App\Imports;

use App\Models\Training;
use Maatwebsite\Excel\Concerns\ToModel;
use Maatwebsite\Excel\Concerns\WithHeadingRow;

class TrainingsImport implements ToModel, WithHeadingRow
{
    public function model(array $row)
    {
        $training = Training::updateOrCreate(
            ['training_no' => $row['training_no']],
            [
                'training_activation' => $row['training_activation'] ?? null,
                'type_of_training' => $row['type_of_training'] ?? null,
                'venue' => $row['venue'] ?? null,
                'name_of_range' => $row['name_of_range'] ?? null,
                'training_region' => $row['training_region'] ?? null,
                'training_s_date' => $row['training_s_date'] ?? null,
                'training_e_date' => $row['training_e_date'] ?? null,
                'training_s_time' => $row['training_s_time'] ?? null,
                'training_e_time' => $row['training_e_time'] ?? null,
                'guest_invitation' => $row['guest_invitation'] ?? null,
                'reg_date' => $row['reg_date'] ?? null,
                'reg_time' => $row['reg_time'] ?? null,
                'office_no' => $row['office_no'] ?? null,
                'floor' => $row['floor'] ?? null,
                'building' => $row['building'] ?? null,
                'block' => $row['block'] ?? null,
                'area' => $row['area'] ?? null,
                'city' => $row['city'] ?? null,
                'photo' => $row['photo'] ?? null,
                'email' => $row['email'] ?? null,
                'website' => $row['website'] ?? null,
                'pin' => $row['pin'] ?? null,
                'gps' => $row['gps'] ?? null,
                'cro_name' => $row['cro_name'] ?? null,
                'cro_cell' => $row['cro_cell'] ?? null,
                'email_cro' => $row['email_cro'] ?? null,
                'organized_by' => $row['organized_by'] ?? null,
                'branch' => $row['branch'] ?? null,
                'demo' => $row['demo'] ?? null,
                'duration' => $row['duration'] ?? null,
                'booking_attach' => $row['booking_attach'] ?? null,
                'all_types_covered' => $row['all_types_covered'] ?? null,
                'reports_submitted' => $row['reports_submitted'] ?? null,
                'booking_request' => $row['booking_request'] ?? null,
                'range_allocation_attach' => $row['range_allocation_attach'] ?? null,
                'booking_request_date' => $row['booking_request_date'] ?? null,
                'copy_booking_attach' => $row['copy_booking_attach'] ?? null,
                'guard_resp_attach' => $row['guard_resp_attach'] ?? null,
                'list_guard_attach' => $row['list_guard_attach'] ?? null,
                'email_active_check' => isset($row['email_active_check']) ? $row['email_active_check'] : false,
                'send_email_active' => $row['send_email_active'] ?? null,
                'email_inactive_check' => isset($row['email_inactive_check']) ? $row['email_inactive_check'] : false,
                'send_email_inactive' => $row['send_email_inactive'] ?? null,
                'email_all_check' => isset($row['email_all_check']) ? $row['email_all_check'] : false,
                'send_email_all' => $row['send_email_all'] ?? null,
                'guards_respective' => $row['guards_respective'] ?? null,
                'date_allocation_letter' => $row['date_allocation_letter'] ?? null,
                'estimated_amount' => $row['estimated_amount'] ?? null,
                'actual_amount' => $row['actual_amount'] ?? null,
                'total_expense' => $row['total_expense'] ?? null,
                'expenses_proof_attach' => $row['expenses_proof_attach'] ?? null,
                'general_check' => isset($row['general_check']) ? $row['general_check'] : false,
                'weapon_check' => isset($row['weapon_check']) ? $row['weapon_check'] : false,
                'frisking_check' => isset($row['frisking_check']) ? $row['frisking_check'] : false,
                'gatehouse_check' => isset($row['gatehouse_check']) ? $row['gatehouse_check'] : false,
                'optimum_check' => isset($row['optimum_check']) ? $row['optimum_check'] : false,
                'radio_check' => isset($row['radio_check']) ? $row['radio_check'] : false,
                'aid_check' => isset($row['aid_check']) ? $row['aid_check'] : false,
                'fire_check' => isset($row['fire_check']) ? $row['fire_check'] : false,
                'self_check' => isset($row['self_check']) ? $row['self_check'] : false,
                'close_check' => isset($row['close_check']) ? $row['close_check'] : false,
                'crime_check' => isset($row['crime_check']) ? $row['crime_check'] : false,
                'general_video' => $row['general_video'] ?? null,
                'general_literature' => $row['general_literature'] ?? null,
                'general_trainer_name' => $row['general_trainer_name'] ?? null,
                'general_trainer_desig' => $row['general_trainer_desig'] ?? null,
                'general_trainer_email' => $row['general_trainer_email'] ?? null,
                'general_trainer_office' => $row['general_trainer_office'] ?? null,
                'general_trainer_rhq' => $row['general_trainer_rhq'] ?? null,
                'general_trainer_region' => $row['general_trainer_region'] ?? null,
                'general_trainer_cards' => $row['general_trainer_cards'] ?? null,
                'general_guards_cards' => $row['general_guards_cards'] ?? null,
                'weapon_video' => $row['weapon_video'] ?? null,
                'weapon_literature' => $row['weapon_literature'] ?? null,
                'weapon_trainer_name' => $row['weapon_trainer_name'] ?? null,
                'weapon_trainer_desig' => $row['weapon_trainer_desig'] ?? null,
                'weapon_trainer_email' => $row['weapon_trainer_email'] ?? null,
                'weapon_trainer_office' => $row['weapon_trainer_office'] ?? null,
                'weapon_trainer_rhq' => $row['weapon_trainer_rhq'] ?? null,
                'weapon_trainer_region' => $row['weapon_trainer_region'] ?? null,
                'weapon_trainer_cards' => $row['weapon_trainer_cards'] ?? null,
                'weapon_guards_cards' => $row['weapon_guards_cards'] ?? null,
                'frisking_video' => $row['frisking_video'] ?? null,
                'frisking_literature' => $row['frisking_literature'] ?? null,
                'frisking_trainer_name' => $row['frisking_trainer_name'] ?? null,
                'frisking_trainer_desig' => $row['frisking_trainer_desig'] ?? null,
                'frisking_trainer_email' => $row['frisking_trainer_email'] ?? null,
                'frisking_trainer_office' => $row['frisking_trainer_office'] ?? null,
                'frisking_trainer_rhq' => $row['frisking_trainer_rhq'] ?? null,
                'frisking_trainer_region' => $row['frisking_trainer_region'] ?? null,
                'frisking_trainer_cards' => $row['frisking_trainer_cards'] ?? null,
                'frisking_guards_cards' => $row['frisking_guards_cards'] ?? null,
                'gatehouse_video' => $row['gatehouse_video'] ?? null,
                'gatehouse_literature' => $row['gatehouse_literature'] ?? null,
                'gatehouse_trainer_name' => $row['gatehouse_trainer_name'] ?? null,
                'gatehouse_trainer_desig' => $row['gatehouse_trainer_desig'] ?? null,
                'gatehouse_trainer_email' => $row['gatehouse_trainer_email'] ?? null,
                'gatehouse_trainer_office' => $row['gatehouse_trainer_office'] ?? null,
                'gatehouse_trainer_rhq' => $row['gatehouse_trainer_rhq'] ?? null,
                'gatehouse_trainer_region' => $row['gatehouse_trainer_region'] ?? null,
                'gatehouse_trainer_cards' => $row['gatehouse_trainer_cards'] ?? null,
                'gatehouse_guards_cards' => $row['gatehouse_guards_cards'] ?? null,
                'optimum_video' => $row['optimum_video'] ?? null,
                'optimum_literature' => $row['optimum_literature'] ?? null,
                'optimum_trainer_name' => $row['optimum_trainer_name'] ?? null,
                'optimum_trainer_desig' => $row['optimum_trainer_desig'] ?? null,
                'optimum_trainer_email' => $row['optimum_trainer_email'] ?? null,
                'optimum_trainer_office' => $row['optimum_trainer_office'] ?? null,
                'optimum_trainer_rhq' => $row['optimum_trainer_rhq'] ?? null,
                'optimum_trainer_region' => $row['optimum_trainer_region'] ?? null,
                'optimum_trainer_cards' => $row['optimum_trainer_cards'] ?? null,
                'optimum_guards_cards' => $row['optimum_guards_cards'] ?? null,
                'radio_video' => $row['radio_video'] ?? null,
                'radio_literature' => $row['radio_literature'] ?? null,
                'radio_trainer_name' => $row['radio_trainer_name'] ?? null,
                'radio_trainer_desig' => $row['radio_trainer_desig'] ?? null,
                'radio_trainer_email' => $row['radio_trainer_email'] ?? null,
                'radio_trainer_office' => $row['radio_trainer_office'] ?? null,
                'radio_trainer_rhq' => $row['radio_trainer_rhq'] ?? null,
                'radio_trainer_region' => $row['radio_trainer_region'] ?? null,
                'radio_trainer_cards' => $row['radio_trainer_cards'] ?? null,
                'radio_guards_cards' => $row['radio_guards_cards'] ?? null,
                'firstaid_video' => $row['firstaid_video'] ?? null,
                'firstaid_literature' => $row['firstaid_literature'] ?? null,
                'firstaid_trainer_name' => $row['firstaid_trainer_name'] ?? null,
                'firstaid_trainer_desig' => $row['firstaid_trainer_desig'] ?? null,
                'firstaid_trainer_email' => $row['firstaid_trainer_email'] ?? null,
                'firstaid_trainer_office' => $row['firstaid_trainer_office'] ?? null,
                'firstaid_trainer_rhq' => $row['firstaid_trainer_rhq'] ?? null,
                'firstaid_trainer_region' => $row['firstaid_trainer_region'] ?? null,
                'firstaid_trainer_cards' => $row['firstaid_trainer_cards'] ?? null,
                'firstaid_guards_cards' => $row['firstaid_guards_cards'] ?? null,
                'fire_video' => $row['fire_video'] ?? null,
                'fire_literature' => $row['fire_literature'] ?? null,
                'fire_trainer_name' => $row['fire_trainer_name'] ?? null,
                'fire_trainer_desig' => $row['fire_trainer_desig'] ?? null,
                'fire_trainer_email' => $row['fire_trainer_email'] ?? null,
                'fire_trainer_office' => $row['fire_trainer_office'] ?? null,
                'fire_trainer_rhq' => $row['fire_trainer_rhq'] ?? null,
                'fire_trainer_region' => $row['fire_trainer_region'] ?? null,
                'fire_trainer_cards' => $row['fire_trainer_cards'] ?? null,
                'fire_guards_cards' => $row['fire_guards_cards'] ?? null,
                'self_video' => $row['self_video'] ?? null,
                'self_literature' => $row['self_literature'] ?? null,
                'self_trainer_name' => $row['self_trainer_name'] ?? null,
                'self_trainer_desig' => $row['self_trainer_desig'] ?? null,
                'self_trainer_email' => $row['self_trainer_email'] ?? null,
                'self_trainer_office' => $row['self_trainer_office'] ?? null,
                'self_trainer_rhq' => $row['self_trainer_rhq'] ?? null,
                'self_trainer_region' => $row['self_trainer_region'] ?? null,
                'self_trainer_cards' => $row['self_trainer_cards'] ?? null,
                'self_guards_cards' => $row['self_guards_cards'] ?? null,
                'close_video' => $row['close_video'] ?? null,
                'close_literature' => $row['close_literature'] ?? null,
                'close_trainer_name' => $row['close_trainer_name'] ?? null,
                'close_trainer_desig' => $row['close_trainer_desig'] ?? null,
                'close_trainer_email' => $row['close_trainer_email'] ?? null,
                'close_trainer_office' => $row['close_trainer_office'] ?? null,
                'close_trainer_rhq' => $row['close_trainer_rhq'] ?? null,
                'close_trainer_region' => $row['close_trainer_region'] ?? null,
                'close_trainer_cards' => $row['close_trainer_cards'] ?? null,
                'close_guards_cards' => $row['close_guards_cards'] ?? null,
                'crime_video' => $row['crime_video'] ?? null,
                'crime_literature' => $row['crime_literature'] ?? null,
                'crime_trainer_name' => $row['crime_trainer_name'] ?? null,
                'crime_trainer_desig' => $row['crime_trainer_desig'] ?? null,
                'crime_trainer_email' => $row['crime_trainer_email'] ?? null,
                'crime_trainer_office' => $row['crime_trainer_office'] ?? null,
                'crime_trainer_rhq' => $row['crime_trainer_rhq'] ?? null,
                'crime_trainer_region' => $row['crime_trainer_region'] ?? null,
                'crime_trainer_cards' => $row['crime_trainer_cards'] ?? null,
                'crime_guards_cards' => $row['crime_guards_cards'] ?? null,
                'first_aid_check' => isset($row['first_aid_check']) ? $row['first_aid_check'] : false,
                'first_aid_quantity' => $row['first_aid_quantity'] ?? null,
                'umbrella_check' => isset($row['umbrella_check']) ? $row['umbrella_check'] : false,
                'umbrella_quantity' => $row['umbrella_quantity'] ?? null,
                'wireless_check' => isset($row['wireless_check']) ? $row['wireless_check'] : false,
                'wireless_quantity' => $row['wireless_quantity'] ?? null,
                'mega_check' => isset($row['mega_check']) ? $row['mega_check'] : false,
                'mega_phone_quantity' => $row['mega_phone_quantity'] ?? null,
                'sofa_check' => isset($row['sofa_check']) ? $row['sofa_check'] : false,
                'sofas_quantity' => $row['sofas_quantity'] ?? null,
                'water_check' => isset($row['water_check']) ? $row['water_check'] : false,
                'watercooler_quantity' => $row['watercooler_quantity'] ?? null,
                'media_attach' => $row['media_attach'] ?? null,
                'media_notes' => $row['media_notes'] ?? null,
                'media_attach_2' => $row['media_attach_2'] ?? null,
                'estimated_amount_loi' => $row['estimated_amount_loi'] ?? null,
                'nearest_hospital' => $row['nearest_hospital'] ?? null,
                'hospital_floor' => $row['hospital_floor'] ?? null,
                'hospital_builduing' => $row['hospital_builduing'] ?? null,
                'hospital_block' => $row['hospital_block'] ?? null,
                'hospital_area' => $row['hospital_area'] ?? null,
                'hospital_city' => $row['hospital_city'] ?? null,
                'hospital_gps' => $row['hospital_gps'] ?? null,
                'hospital_pic' => $row['hospital_pic'] ?? null,
                'incident_attach' => $row['incident_attach'] ?? null,
                'incident_notes' => $row['incident_notes'] ?? null,
                'suggestion_attach' => $row['suggestion_attach'] ?? null,
                'suggestion_notes' => $row['suggestion_notes'] ?? null,
                'observation_attach' => $row['observation_attach'] ?? null,
                'observation_notes' => $row['observation_notes'] ?? null,
                'remarks_attach' => $row['remarks_attach'] ?? null,
                'remarks_notes' => $row['remarks_notes'] ?? null,
                't_range_name' => $row['t_range_name'] ?? null,
                't_range_desig' => $row['t_range_desig'] ?? null,
                't_range_dept' => $row['t_range_dept'] ?? null,
                't_range_cell' => $row['t_range_cell'] ?? null,
                't_range_email' => $row['t_range_email'] ?? null,
                't_range_front' => $row['t_range_front'] ?? null,
                't_range_back' => $row['t_range_back'] ?? null,
                't_range_office' => $row['t_range_office'] ?? null,
                't_range_floor' => $row['t_range_floor'] ?? null,
                't_range_building' => $row['t_range_building'] ?? null,
                't_range_block' => $row['t_range_block'] ?? null,
                't_range_area' => $row['t_range_area'] ?? null,
                't_range_city' => $row['t_range_city'] ?? null,
                't_range_photo' => $row['t_range_photo'] ?? null,
                'adress_range_email' => $row['adress_range_email'] ?? null,
                't_range_web' => $row['t_range_web'] ?? null,
                't_range_pin' => $row['t_range_pin'] ?? null,
                't_range_gps' => $row['t_range_gps'] ?? null,
                'point_one_check' => isset($row['point_one_check']) ? $row['point_one_check'] : false,
                'point_one' => $row['point_one'] ?? null,
                'point_two_check' => isset($row['point_two_check']) ? $row['point_two_check'] : false,
                'point_two' => $row['point_two'] ?? null,
                'point_three_check' => isset($row['point_three_check']) ? $row['point_three_check'] : false,
                'point_three' => $row['point_three'] ?? null,
                'point_four_check' => isset($row['point_four_check']) ? $row['point_four_check'] : false,
                'point_four' => $row['point_four'] ?? null,
                'point_five_check' => isset($row['point_five_check']) ? $row['point_five_check'] : false,
                'point_five' => $row['point_five'] ?? null,
                'point_six_check' => isset($row['point_six_check']) ? $row['point_six_check'] : false,
                'point_six' => $row['point_six'] ?? null,
                'point_seven_check' => isset($row['point_seven_check']) ? $row['point_seven_check'] : false,
                'point_seven' => $row['point_seven'] ?? null,
                'point_eight_check' => isset($row['point_eight_check']) ? $row['point_eight_check'] : false,
                'point_eight' => $row['point_eight'] ?? null,
                'point_nine_check' => isset($row['point_nine_check']) ? $row['point_nine_check'] : false,
                'point_nine' => $row['point_nine'] ?? null,
                'point_ten_check' => isset($row['point_ten_check']) ? $row['point_ten_check'] : false,
                'point_ten' => $row['point_ten'] ?? null,
                'point_eleven_check' => isset($row['point_eleven_check']) ? $row['point_eleven_check'] : false,
                'point_eleven' => $row['point_eleven'] ?? null,
                'point_twelve_check' => isset($row['point_twelve_check']) ? $row['point_twelve_check'] : false,
                'point_twelve' => $row['point_twelve'] ?? null,
                'point_thirteen_check' => isset($row['point_thirteen_check']) ? $row['point_thirteen_check'] : false,
                'point_thirteen' => $row['point_thirteen'] ?? null,
                'point_forteen_check' => isset($row['point_forteen_check']) ? $row['point_forteen_check'] : false,
                'point_forteen' => $row['point_forteen'] ?? null,
                'point_fifteen_check' => isset($row['point_fifteen_check']) ? $row['point_fifteen_check'] : false,
                'point_fifteen' => $row['point_fifteen'] ?? null,
                'point_sixteen_check' => isset($row['point_sixteen_check']) ? $row['point_sixteen_check'] : false,
                'point_sixteen' => $row['point_sixteen'] ?? null,
                'point_seventeen_check' => isset($row['point_seventeen_check']) ? $row['point_seventeen_check'] : false,
                'point_seventeen' => $row['point_seventeen'] ?? null,
                'point_eighteen_check' => isset($row['point_eighteen_check']) ? $row['point_eighteen_check'] : false,
                'point_eighteen' => $row['point_eighteen'] ?? null,
                'point_ninteen_check' => isset($row['point_ninteen_check']) ? $row['point_ninteen_check'] : false,
                'point_ninteen' => $row['point_ninteen'] ?? null,
                'point_twenty_check' => isset($row['point_twenty_check']) ? $row['point_twenty_check'] : false,
                'point_twenty' => $row['point_twenty'] ?? null,
                'point_twentyone_check' => isset($row['point_twentyone_check']) ? $row['point_twentyone_check'] : false,
                'point_twentyone' => $row['point_twentyone'] ?? null,
                'point_twentytwo_check' => isset($row['point_twentytwo_check']) ? $row['point_twentytwo_check'] : false,
                'point_twentytwo' => $row['point_twentytwo'] ?? null,
                'point_twentythree_check' => isset($row['point_twentythree_check']) ? $row['point_twentythree_check'] : false,
                'point_twentythree' => $row['point_twentythree'] ?? null,
                'point_twentyfour_check' => isset($row['point_twentyfour_check']) ? $row['point_twentyfour_check'] : false,
                'point_twentyfour' => $row['point_twentyfour'] ?? null,
                'point_twentyfive_check' => isset($row['point_twentyfive_check']) ? $row['point_twentyfive_check'] : false,
                'point_twentyfive' => $row['point_twentyfive'] ?? null,
                'point_twentysix_check' => isset($row['point_twentysix_check']) ? $row['point_twentysix_check'] : false,
                'point_twentysix' => $row['point_twentysix'] ?? null,
            ]
        );

        if ($training) {
            $training->trainingbudgets()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'out_of_scope' => isset($row['out_of_scope']) ? $row['out_of_scope'] : false,
                    'budget_category' => $row['budget_category'] ?? null,
                    'mode_of_payment' => $row['mode_of_payment'] ?? null,
                    'budget_ins_no' => $row['budget_ins_no'] ?? null,
                    'name_of_bank' => $row['name_of_bank'] ?? null,
                    'date_of_payment' => $row['date_of_payment'] ?? null,
                    'amount_per_unit' => $row['amount_per_unit'] ?? null,
                    'quantity' => $row['quantity'] ?? null,
                    'total_amount' => $row['total_amount'] ?? null,
                    'cheque_attach' => $row['cheque_attach'] ?? null,
                    'voucher_attach' => $row['voucher_attach'] ?? null,
                ]
            );

            $training->trainingweapons()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'type_of_weapon' => $row['type_of_weapon'] ?? null,
                    'weapon_no' => $row['weapon_no'] ?? null,
                    'caliber' => $row['caliber'] ?? null,
                    'bore' => $row['bore'] ?? null,
                    'weapon_price_pu' => $row['weapon_price_pu'] ?? null,
                    'weapon_total_price' => $row['weapon_total_price'] ?? null,
                    'weapon_quantity' => $row['weapon_quantity'] ?? null,
                    'person_responsible_weapon' => $row['person_responsible_weapon'] ?? null,
                    'weapon_attach' => $row['weapon_attach'] ?? null,
                    'weapon_notes' => $row['weapon_notes'] ?? null,
                ]
            );

            $training->trainingammunitions()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'ammu_quantity' => $row['ammu_quantity'] ?? null,
                    'ammu_type' => $row['ammu_type'] ?? null,
                    'person_responsible_ammu' => $row['person_responsible_ammu'] ?? null,
                    'price_per_unit_ammu' => $row['price_per_unit_ammu'] ?? null,
                    'total_price_ammu' => $row['total_price_ammu'] ?? null,
                    'ammu_attach' => $row['ammu_attach'] ?? null,
                    'ammu_notes' => $row['ammu_notes'] ?? null,
                ]
            );

            $training->trainingarmourers()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'armourer_name' => $row['armourer_name'] ?? null,
                    'armourer_cell' => $row['armourer_cell'] ?? null,
                    'armourer_attach' => $row['armourer_attach'] ?? null,
                    'armourer_notes' => $row['armourer_notes'] ?? null,
                ]
            );

            $training->trainingequipments()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'sec_equip_category' => $row['sec_equip_category'] ?? null,
                    'sec_equip_type' => $row['sec_equip_type'] ?? null,
                    'sec_equip_pricepu' => $row['sec_equip_pricepu'] ?? null,
                    'sec_equip_quantity' => $row['sec_equip_quantity'] ?? null,
                    'sec_equip_totalprice' => $row['sec_equip_totalprice'] ?? null,
                    'person_responsible_sec_equip' => $row['person_responsible_sec_equip'] ?? null,
                    'sec_equip_attach' => $row['sec_equip_attach'] ?? null,
                    'sec_equip_notes' => $row['sec_equip_notes'] ?? null,
                    'red_flag_quantity' => $row['red_flag_quantity'] ?? null,
                    'target_quantity' => $row['target_quantity'] ?? null,
                ]
            );

            $training->trainingitems()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'list_items_category' => $row['list_items_category'] ?? null,
                    'item_category' => $row['item_category'] ?? null,
                    'item_type' => $row['item_type'] ?? null,
                    'item_supplier' => $row['item_supplier'] ?? null,
                    'item_quantity' => $row['item_quantity'] ?? null,
                    'item_price' => $row['item_price'] ?? null,
                    'item_total_price' => $row['item_total_price'] ?? null,
                    'item_notes' => $row['item_notes'] ?? null,
                    'item_attach' => $row['item_attach'] ?? null,
                    'item_vendor' => $row['item_vendor'] ?? null,
                    'vendor_cell' => $row['vendor_cell'] ?? null,
                    'vendor_floor' => $row['vendor_floor'] ?? null,
                    'vendor_building' => $row['vendor_building'] ?? null,
                    'vendor_block' => $row['vendor_block'] ?? null,
                    'vendor_area' => $row['vendor_area'] ?? null,
                    'vendor_city' => $row['vendor_city'] ?? null,
                    'vendor_email' => $row['vendor_email'] ?? null,
                    'vendor_website' => $row['vendor_website'] ?? null,
                    'vendor_gps' => $row['vendor_gps'] ?? null,
                    'vendor_notes' => $row['vendor_notes'] ?? null,
                    'vendor_attach' => $row['vendor_attach'] ?? null,
                ]
            );

            $training->trainingemergencies()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'train_emer_ser' => $row['train_emer_ser'] ?? null,
                    'train_emer_pic' => $row['train_emer_pic'] ?? null,
                    'train_emer_poc_name' => $row['train_emer_poc_name'] ?? null,
                    'train_emer_poc_desig' => $row['train_emer_poc_desig'] ?? null,
                    'train_emer_poc_cell' => $row['train_emer_poc_cell'] ?? null,
                    'train_emer_poc_email' => $row['train_emer_poc_email'] ?? null,
                    'train_emer_poc_notes' => $row['train_emer_poc_notes'] ?? null,
                    'train_emer_poc_attach' => $row['train_emer_poc_attach'] ?? null,
                    'train_emer_office' => $row['train_emer_office'] ?? null,
                    'train_emer_building' => $row['train_emer_building'] ?? null,
                    'train_emer_block' => $row['train_emer_block'] ?? null,
                    'train_emer_area' => $row['train_emer_area'] ?? null,
                    'train_emer_city' => $row['train_emer_city'] ?? null,
                    'train_emer_buildphoto' => $row['train_emer_buildphoto'] ?? null,
                    'train_emer_email' => $row['train_emer_email'] ?? null,
                    'train_emer_web' => $row['train_emer_web'] ?? null,
                    'train_emer_pin' => $row['train_emer_pin'] ?? null,
                    'train_emer_app_rental' => $row['train_emer_app_rental'] ?? null,
                    'train_emer_attach' => $row['train_emer_attach'] ?? null,
                    'train_emer_note' => $row['train_emer_note'] ?? null,
                ]
            );

            $training->trainingpocs()->updateOrCreate(
                ['trainings_id' => $training->id],
                [
                    'poc_name' => $row['poc_name'] ?? null,
                    'poc_desig' => $row['poc_desig'] ?? null,
                    'poc_fax' => $row['poc_fax'] ?? null,
                    'poc_phone' => $row['poc_phone'] ?? null,
                    'poc_mobile' => $row['poc_mobile'] ?? null,
                    'poc_web' => $row['poc_web'] ?? null,
                    'poc_email' => $row['poc_email'] ?? null,
                    'poc_loc' => $row['poc_loc'] ?? null,
                    'poc_document' => $row['poc_document'] ?? null,
                    'system_id' => $row['system_id'] ?? null,
                    'other_info' => $row['other_info'] ?? null,
                ]
            );
        }

        return $training;
    }
}
